/**
 * Full list of country calling codes for user phone inputs.
 * `code` is the dial prefix (e.g. "+1"), `value` is ISO 3166-1 alpha-2.
 */
export interface CountryCode {
  code: string
  value: string
  label: string
}

export const COUNTRY_CODES: CountryCode[] = [
  { code: '+1', value: 'US', label: 'United States' },
  { code: '+1', value: 'CA', label: 'Canada' },
  { code: '+44', value: 'GB', label: 'United Kingdom' },
  { code: '+61', value: 'AU', label: 'Australia' },
  { code: '+49', value: 'DE', label: 'Germany' },
  { code: '+33', value: 'FR', label: 'France' },
  { code: '+34', value: 'ES', label: 'Spain' },
  { code: '+39', value: 'IT', label: 'Italy' },
  { code: '+31', value: 'NL', label: 'Netherlands' },
  { code: '+32', value: 'BE', label: 'Belgium' },
  { code: '+41', value: 'CH', label: 'Switzerland' },
  { code: '+43', value: 'AT', label: 'Austria' },
  { code: '+46', value: 'SE', label: 'Sweden' },
  { code: '+47', value: 'NO', label: 'Norway' },
  { code: '+45', value: 'DK', label: 'Denmark' },
  { code: '+358', value: 'FI', label: 'Finland' },
  { code: '+353', value: 'IE', label: 'Ireland' },
  { code: '+351', value: 'PT', label: 'Portugal' },
  { code: '+30', value: 'GR', label: 'Greece' },
  { code: '+48', value: 'PL', label: 'Poland' },
  { code: '+420', value: 'CZ', label: 'Czech Republic' },
  { code: '+36', value: 'HU', label: 'Hungary' },
  { code: '+40', value: 'RO', label: 'Romania' },
  { code: '+7', value: 'RU', label: 'Russia' },
  { code: '+380', value: 'UA', label: 'Ukraine' },
  { code: '+90', value: 'TR', label: 'Turkey' },
  { code: '+972', value: 'IL', label: 'Israel' },
  { code: '+971', value: 'AE', label: 'United Arab Emirates' },
  { code: '+966', value: 'SA', label: 'Saudi Arabia' },
  { code: '+20', value: 'EG', label: 'Egypt' },
  { code: '+27', value: 'ZA', label: 'South Africa' },
  { code: '+234', value: 'NG', label: 'Nigeria' },
  { code: '+254', value: 'KE', label: 'Kenya' },
  { code: '+212', value: 'MA', label: 'Morocco' },
  { code: '+91', value: 'IN', label: 'India' },
  { code: '+92', value: 'PK', label: 'Pakistan' },
  { code: '+880', value: 'BD', label: 'Bangladesh' },
  { code: '+94', value: 'LK', label: 'Sri Lanka' },
  { code: '+977', value: 'NP', label: 'Nepal' },
  { code: '+86', value: 'CN', label: 'China' },
  { code: '+81', value: 'JP', label: 'Japan' },
  { code: '+82', value: 'KR', label: 'South Korea' },
  { code: '+65', value: 'SG', label: 'Singapore' },
  { code: '+60', value: 'MY', label: 'Malaysia' },
  { code: '+66', value: 'TH', label: 'Thailand' },
  { code: '+84', value: 'VN', label: 'Vietnam' },
  { code: '+62', value: 'ID', label: 'Indonesia' },
  { code: '+63', value: 'PH', label: 'Philippines' },
  { code: '+64', value: 'NZ', label: 'New Zealand' },
  { code: '+52', value: 'MX', label: 'Mexico' },
  { code: '+55', value: 'BR', label: 'Brazil' },
  { code: '+54', value: 'AR', label: 'Argentina' },
  { code: '+56', value: 'CL', label: 'Chile' },
  { code: '+57', value: 'CO', label: 'Colombia' },
  { code: '+51', value: 'PE', label: 'Peru' },
  { code: '+58', value: 'VE', label: 'Venezuela' },
  { code: '+598', value: 'UY', label: 'Uruguay' },
  { code: '+593', value: 'EC', label: 'Ecuador' },
  { code: '+506', value: 'CR', label: 'Costa Rica' },
  { code: '+507', value: 'PA', label: 'Panama' },
  { code: '+502', value: 'GT', label: 'Guatemala' },
  { code: '+504', value: 'HN', label: 'Honduras' },
  { code: '+503', value: 'SV', label: 'El Salvador' },
  { code: '+505', value: 'NI', label: 'Nicaragua' },
  { code: '+591', value: 'BO', label: 'Bolivia' },
  { code: '+595', value: 'PY', label: 'Paraguay' },
]

export const DEFAULT_COUNTRY = 'US'
